import Menu from '@/components/molecules/Menu';
import Navbar from '@/components/atoms/Navbar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Parnaioca - Painel Administrativo',
  description: 'Generated by create next app',
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Menu />
      <Navbar />
      {children}
    </>
  );
}
