services:

  apiparnaiocadb:
    image: mongo:8.0.12
    restart: always
    container_name: apiparnaiocadb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - apiparnaioca-network

  apiparnaiocadb_interface_grafica:
    image: mongo-express
    restart: always
    container_name: apiparnaiocadb_interface_grafica
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@apiparnaiocadb:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - apiparnaioca-network

networks:
  apiparnaioca-network:
    driver: bridge
